### PR TITLE
add my uncle terry everyone say hi terry

### PR DESCRIPTION
**Pull request by pixieclaws**
terry

### CODE REVIEW

**Comment by Xameren** [comment]
Hi Terry

**Comment by authenyoo** [comment]
hi terry

**Comment by jjj333-p** [comment]
Hi terry

Bro didn’t even link it in the read me or shit 😭😭

**Comment by TruncatedDinoSour** [comment]
hi terry

**Comment by Z-A-Y-D** [comment]
LGTM

**Comment by mcneb10** [comment]
@jjj333-p please reopen the pr

**Comment by mcneb10** [comment]
This upstanding gentleman deserves to be merged

**Comment by mcneb10** [comment]
He did nothing wrong

**Comment by mcneb10** [comment]
He did nothing wrong and they closed his PR

**Comment by Z-A-Y-D** [comment]
@jjj333-p OPEN THE PR FREE MY MAN TERRY

**Comment by jjj333-p** [comment]
brb while i figure out how to lock a pr

**Comment by Z-A-Y-D** [comment]
> brb while i figure out how to lock a pr

No.

**Pull request closed without merging**
