### PR TITLE
add alpha oil o oospeak

### PR DESCRIPTION
**Pull request by TruncatedDinoSour**
my keyoad is oken :(

### CODE REVIEW

**Review by TruncatedDinoSour — COMMENTED** [review]
L ! ( keyoad oken )

**Comment by jjj333-p** [comment]
Ok.

**Comment by everypizza1** [comment]
LGTM 🚀🚀🚀

**Review by TruncatedDinoSour — COMMENTED** [review]
LGBT! (with a less broken keyboard)

**Pull request merged**
